/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package T1_SegurancaSistemas;

import org.junit.Test;

import static org.junit.Assert.*;

public class DecifradorTest {
	
	@Test
	public void testSomeLibraryMethod() {

	}
}
